version: '3.8'

services:
  python_app:
    build:
      context: ./.docker/python/
    container_name: python_app
    volumes:
      - ./admin-python:/usr/src/app
    working_dir: /usr/src/app
    command: bash -c "pipenv run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: