version: '3.8'

services:
  nginx:
    image: nginx:1.19.10-alpine
    container_name: nginx
    ports:
      - 9000:9000
    volumes:
      - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - external-storage:/media/uploads

  app_nextjs:
    build:
      context: ./.docker/nextjs/
    container_name: app_nextjs
    working_dir: /app
    volumes:
      - ./frontend-nextjs:/app
    command: sh -c "npm install -y && npm run dev"
    # command: tail -f /dev/null
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    depends_on:
      - python_app

  python_app:
    build:
      context: ./.docker/python/
    container_name: python_app
    volumes:
      - ./admin-python:/usr/src/app
      - external-storage:/media/uploads
    working_dir: /usr/src/app
    command: sh -c "pipenv install && pipenv run python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - nginx
      - db
      - rabbitmq
    env_file:
      - ./.env

  conversor_go:
    build:
      context: ./.docker/conversor-go/
    container_name: conversor_go
    working_dir: /app
    env_file:
      - ./.env
    volumes:
      - ./conversor-go:/app
      - external-storage:/media/uploads
    tty: true
    stdin_open: true
    # command: go run cmd/videoconverter/main.go
    command: tail -f /dev/null
    ports:
      - "8083:8080"
    depends_on:
      - db
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
     - ./.env

  db:
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    env_file:
     - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  external-storage: 
    external: true